### ISSUE TITLE
Error installing via composer

### ISSUE THREAD

**Issue by synapze** [wbraganca/yii2-mmenu-widget#1]
<b>After running:</b>
<code>composer require wbraganca/yii2-mmenu-widget "*"</code>

<b>I get the following error:</b>

<code>Your requirements could not be resolved to an installable set of packages.</code>

  <code>Problem 1
    - The requested package wbraganca/yii2-mmenu-widget could not be found in any version, there may be a typo in the package name.
</code>

Any ideas?

**Comment by wbraganca** [comment]
Tagged v1.0.0

**Comment by synapze** [comment]
_UPDATE_ - It seems your composer.json file is fine but packagist has not registered the case sensitive change to the name.

The bower asset name for <b>Jquery.mmenu</b> might be incorrect. I believe bower package names are case sensitive.  The bower website has it as <b>jQuery.mmenu</b>.

<b>I'm now getting the following:</b>

<code>Your requirements could not be resolved to an installable set of packages.</code>

<code>   Problem 1</code>
<code>   - Installation request for wbraganca/yii2-mmenu-widget \* -> satisfiable by wbraganca/yii2-mmenu-widget[v1.0.0].</code>
<code>    - wbraganca/yii2-mmenu-widget v1.0.0 requires bower-asset/jquery.mmenu \* -> no matching package found.</code>
